name: Latest Repos
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: matchai/latest-repos@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          count: 3 # Ini akan menampilkan 3 repo terbaru
