name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *' # Update setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-cards
    steps:
      - uses: vn7n24hlkvq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 7 # Sesuaikan dengan zona waktu WIB
